/**
 * @fileoverview Barrel export file for all TypeScript type definitions
 * @author PlebDevs Team
 * @version 1.0.0
 * @since 2024-01-01
 */

// Authentication and user types
export type {
  User,
  Role,
  PlatformNip05,
  PlatformLightningAddress,
  Account,
  Session,
  AuthProvider,
  SubscriptionType,
  UserWithDetails,
  AuthContextType,
  EmailCredentials,
  NostrCredentials,
  GitHubCredentials,
  LoginCredentials,
} from './auth';

// Content and course types
export type {
  Resource,
  Course,
  Lesson,
  Draft,
  CourseDraft,
  DraftLesson,
  UserLesson,
  UserCourse,
  Purchase,
  Badge,
  UserBadge,
  ContentType,
  DraftType,
  CourseWithDetails,
  ResourceWithDetails,
  LessonWithDetails,
  DraftWithDetails,
  CourseDraftWithDetails,
  ContentFilters,
  ContentSearchParams,
  CreateCourseRequest,
  CreateResourceRequest,
  CreateDraftRequest,
  UserProgress,
  CourseProgress,
  ContentStats,
} from './content';

// API types
export type {
  APIResponse,
  PaginatedResponse,
  APIError,
  ValidationError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  ConflictError,
  RateLimitError,
  PaginationParams,
  SearchParams,
  APIEndpoints,
  APIMethod,
  APIRouteConfig,
  ExtractAPIParams,
  ExtractAPIQuery,
  ExtractAPIBody,
  ExtractAPIResponse,
} from './api';

// UI component types
export type {
  BaseComponentProps,
  PageLayoutProps,
  HeaderProps,
  FooterProps,
  SidebarProps,
  ContentCardProps,
  CourseCardProps,
  ContentGridProps,
  ContentCarouselProps,
  FormFieldProps,
  SearchBarProps,
  FiltersPanelProps,
  LoginModalProps,
  SignupFormProps,
  SignupFormData,
  ProfileFormProps,
  AdminDashboardProps,
  ContentEditorProps,
  ThemeEditorProps,
  ProgressBarProps,
  ProgressDashboardProps,
  AnalyticsChartProps,
  ModalProps,
  ConfirmDialogProps,
  NavigationProps,
  NavigationItem,
  ButtonProps,
  ActionMenuProps,
  ActionMenuItem,
  ToastProps,
  LoadingSpinnerProps,
  EmptyStateProps,
  ThemeConfig,
  ComponentVariantConfig,
  ClickHandler,
  ChangeHandler,
  SubmitHandler,
  KeyboardHandler,
  Breakpoint,
  ResponsiveValue,
  AnimationConfig,
  TransitionType,
} from './ui';
